export const Event = {
    SELECT: 'select',
    ADD_OBJECT: 'add_object',
    REMOVE_OBJECT: 'remove_object',
    VISIBLE_CHANGE: 'visible_change',
    USER_DATA_CHANGE: 'user_data_change',
    DIMENSION_CHANGE: 'dimension_change',
    DIMENSION_CHANGE_BEFORE: 'dimension_change_before',
    DIMENSION_CHANGE_AFTER: 'dimension_change_after',
    CONTAINER_TRANSFORM: 'container_transform',
    CLEAR_DATA: 'clear_data',
    SHOW_CLASS_INFO: 'show_class_info',
    CLICK_LABEL: 'click_label',
    LOAD_OBJECTS: 'load_objects',
    IMAGE_LOADED: 'image_loaded',
    ZOOM_CHANGE: 'zoom_change',
    UNDO: 'undo',
    REDO: 'redo',
    RESET: 'reset',
    EXECUTE: 'execute',
    FILTER_CHANGE: 'filter_change',
    FILTER_TOGGLE: 'filter_toggle',
    IMAGE_CHANGE: 'image_change',
    RESET_SELECT: 'reset_select',
};
export default Event;
